version: "3.8"
services:
  app:
    container_name: "user-mana-container"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres-container-13:5432/user_management_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgres-container-13"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "user_management_db"

volumes:
  postgres-data: